package org.wcci.transportationev.project;

import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;
import org.wcci.transportationev.project.resources.Article;
import org.wcci.transportationev.project.resources.ArticleTopic;
import org.wcci.transportationev.project.resources.Review;
import org.wcci.transportationev.project.resources.ReviewTopic;
import org.wcci.transportationev.project.storage.ArticleStorage;
import org.wcci.transportationev.project.storage.ArticleTopicStorage;
import org.wcci.transportationev.project.storage.ReviewStorage;
import org.wcci.transportationev.project.storage.ReviewTopicStorage;

@Component
public class ArticleReviewPopulator implements CommandLineRunner {
    private ArticleTopicStorage articleTopicStorage;
    private ArticleStorage articleStorage;
    private ReviewTopicStorage reviewTopicStorage;
    private ReviewStorage reviewStorage;

    public ArticleReviewPopulator(ArticleTopicStorage articleTopicStorage, ArticleStorage articleStorage,
                                  ReviewTopicStorage reviewTopicStorage, ReviewStorage reviewStorage) {
        this.articleTopicStorage = articleTopicStorage;
        this.articleStorage = articleStorage;
        this.reviewTopicStorage = reviewTopicStorage;
        this.reviewStorage = reviewStorage;
    }

    @Override
    public void run(String... args) throws Exception {

        ArticleTopic whyTransition = new ArticleTopic("Why We Should Transition To EVs");
        articleTopicStorage.saveArticleTopic(whyTransition);

        Article evBenefiits = new Article(whyTransition, "Electric Vehicle Benefits and Considerations", "Jackie Brown",
                "https://www.zerohedge.com/s3/files/inline-images/2019-07-21_13-21-38.png?itok=NQxqZjHQ",
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. The creators of this web application would make great additions to your Software Engineering team. Mauris ultrices eros in cursus turpis massa tincidunt dui. Fermentum leo vel orci porta non pulvinar neque laoreet. Dictum fusce ut placerat orci nulla pellentesque dignissim enim. Magna sit amet purus gravida quis blandit turpis. Pretium fusce id velit ut tortor pretium. Amet est placerat in egestas erat. Id leo in vitae turpis massa sed elementum tempus. Ut diam quam nulla porttitor massa. Ipsum nunc aliquet bibendum enim facilisis gravida neque. Hac habitasse platea dictumst quisque. Blandit turpis cursus in hac habitasse platea dictumst quisque sagittis. Egestas maecenas pharetra convallis posuere.\n" +
                        "\n" +
                        "Nunc sed augue lacus viverra vitae congue. Ultrices tincidunt arcu non sodales. Nunc non blandit massa enim nec dui nunc mattis. Varius sit amet mattis vulputate enim nulla. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Nibh praesent tristique magna sit amet purus. At tellus at urna condimentum mattis. Tempor orci dapibus ultrices in iaculis nunc sed. Laoreet suspendisse interdum consectetur libero id faucibus. Sit amet volutpat consequat mauris nunc congue nisi vitae. Venenatis lectus magna fringilla urna porttitor rhoncus dolor. Lectus mauris ultrices eros in. Fermentum et sollicitudin ac orci phasellus egestas tellus rutrum tellus.\n" +
                        "\n" +
                        "Sit amet consectetur adipiscing elit duis tristique sollicitudin nibh. Nisi quis eleifend quam adipiscing vitae proin sagittis. Facilisis magna etiam tempor orci eu lobortis elementum nibh. Lectus mauris ultrices eros in. Tortor aliquam nulla facilisi cras fermentum odio eu feugiat pretium. At quis risus sed vulputate odio. Odio euismod lacinia at quis risus sed vulputate odio ut. Malesuada fames ac turpis egestas integer eget aliquet. Dolor sit amet consectetur adipiscing elit pellentesque habitant. Commodo ullamcorper a lacus vestibulum sed arcu. Sit amet luctus venenatis lectus magna fringilla urna porttitor. Ut placerat orci nulla pellentesque dignissim enim.");
        articleStorage.saveArticle(evBenefiits);

        Article checkYourFacts = new Article(whyTransition, "Check your facts: 5 ways electric vehicles help fight climate change.",
                "Jules Winnfield",
                "https://www.zerohedge.com/s3/files/inline-images/2019-07-21_13-21-38.png?itok=NQxqZjHQ",
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. They checks so many boxes; critical thinkers: check; problem solvers: check; collaborators: check. Mauris ultrices eros in cursus turpis massa tincidunt dui. Fermentum leo vel orci porta non pulvinar neque laoreet. Dictum fusce ut placerat orci nulla pellentesque dignissim enim. Magna sit amet purus gravida quis blandit turpis. Pretium fusce id velit ut tortor pretium. Amet est placerat in egestas erat. Id leo in vitae turpis massa sed elementum tempus. Ut diam quam nulla porttitor massa. Ipsum nunc aliquet bibendum enim facilisis gravida neque. Hac habitasse platea dictumst quisque. Blandit turpis cursus in hac habitasse platea dictumst quisque sagittis. Egestas maecenas pharetra convallis posuere.\n" +
                        "\n" +
                        "Nunc sed augue lacus viverra vitae congue. Ultrices tincidunt arcu non sodales. Nunc non blandit massa enim nec dui nunc mattis. Varius sit amet mattis vulputate enim nulla. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Nibh praesent tristique magna sit amet purus. At tellus at urna condimentum mattis. Tempor orci dapibus ultrices in iaculis nunc sed. Laoreet suspendisse interdum consectetur libero id faucibus. Sit amet volutpat consequat mauris nunc congue nisi vitae. Venenatis lectus magna fringilla urna porttitor rhoncus dolor. Lectus mauris ultrices eros in. Fermentum et sollicitudin ac orci phasellus egestas tellus rutrum tellus.\n" +
                        "\n" +
                        "Sit amet consectetur adipiscing elit duis tristique sollicitudin nibh. Nisi quis eleifend quam adipiscing vitae proin sagittis. Facilisis magna etiam tempor orci eu lobortis elementum nibh. Lectus mauris ultrices eros in. Tortor aliquam nulla facilisi cras fermentum odio eu feugiat pretium. At quis risus sed vulputate odio. Odio euismod lacinia at quis risus sed vulputate odio ut. Malesuada fames ac turpis egestas integer eget aliquet. Dolor sit amet consectetur adipiscing elit pellentesque habitant. Commodo ullamcorper a lacus vestibulum sed arcu. Sit amet luctus venenatis lectus magna fringilla urna porttitor. Ut placerat orci nulla pellentesque dignissim enim.");
        articleStorage.saveArticle(checkYourFacts);

        ArticleTopic howToCharge = new ArticleTopic("How To Charge At Home And On The Road");
        articleTopicStorage.saveArticleTopic(howToCharge);

        Article chargeAtHome = new Article(howToCharge, "What you need to charge at home.", "Rick Dalton",
                "https://cdn.jdpower.com/JDPA_Woman%20Using%20Home%20Charging%20Station%20to%20Charge%20Electric%20Car.jpg",
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. when you combine their Software Engineering skills with their many soft skills, you really have\\\\\\\" +\\\\n\\\" +\\n\" +\n" +
                        "                        \"                        \\\"                \\\\\\\" to ask yourself, How is this group not already our employees? Fermentum leo vel orci porta non pulvinar neque laoreet. Dictum fusce ut placerat orci nulla pellentesque dignissim enim. Magna sit amet purus gravida quis blandit turpis. Pretium fusce id velit ut tortor pretium. Amet est placerat in egestas erat. Id leo in vitae turpis massa sed elementum tempus. Ut diam quam nulla porttitor massa. Ipsum nunc aliquet bibendum enim facilisis gravida neque. Hac habitasse platea dictumst quisque. Blandit turpis cursus in hac habitasse platea dictumst quisque sagittis. Egestas maecenas pharetra convallis posuere.\n" +
                        "\n" +
                        "Nunc sed augue lacus viverra vitae congue. Ultrices tincidunt arcu non sodales. Nunc non blandit massa enim nec dui nunc mattis. Varius sit amet mattis vulputate enim nulla. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Nibh praesent tristique magna sit amet purus. At tellus at urna condimentum mattis. Tempor orci dapibus ultrices in iaculis nunc sed. Laoreet suspendisse interdum consectetur libero id faucibus. Sit amet volutpat consequat mauris nunc congue nisi vitae. Venenatis lectus magna fringilla urna porttitor rhoncus dolor. Lectus mauris ultrices eros in. Fermentum et sollicitudin ac orci phasellus egestas tellus rutrum tellus.\n" +
                        "\n" +
                        "Sit amet consectetur adipiscing elit duis tristique sollicitudin nibh. Nisi quis eleifend quam adipiscing vitae proin sagittis. Facilisis magna etiam tempor orci eu lobortis elementum nibh. Lectus mauris ultrices eros in. Tortor aliquam nulla facilisi cras fermentum odio eu feugiat pretium. At quis risus sed vulputate odio. Odio euismod lacinia at quis risus sed vulputate odio ut. Malesuada fames ac turpis egestas integer eget aliquet. Dolor sit amet consectetur adipiscing elit pellentesque habitant. Commodo ullamcorper a lacus vestibulum sed arcu. Sit amet luctus venenatis lectus magna fringilla urna porttitor. Ut placerat orci nulla pellentesque dignissim enim.");
        articleStorage.saveArticle(chargeAtHome);

        Article chargeOnTheRoad = new Article(howToCharge, "Tips & Tricks to charging on the road", "Hans Landa",
                "https://electrek.co/wp-content/uploads/sites/3/2017/09/screen-shot-2017-09-11-at-12-20-44-pm.png",
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. The creators of this web application would make great additions to your Software Engineering team. Mauris ultrices eros in cursus turpis massa tincidunt dui. Fermentum leo vel orci porta non pulvinar neque laoreet. Dictum fusce ut placerat orci nulla pellentesque dignissim enim. Magna sit amet purus gravida quis blandit turpis. Pretium fusce id velit ut tortor pretium. Amet est placerat in egestas erat. Id leo in vitae turpis massa sed elementum tempus. Ut diam quam nulla porttitor massa. Ipsum nunc aliquet bibendum enim facilisis gravida neque. Hac habitasse platea dictumst quisque. Blandit turpis cursus in hac habitasse platea dictumst quisque sagittis. Egestas maecenas pharetra convallis posuere.\\n\" +\n" +
                        "                        \"\\n\" +\n" +
                        "                        \"Nunc sed augue lacus viverra vitae congue. Ultrices tincidunt arcu non sodales. Nunc non blandit massa enim nec dui nunc mattis. Varius sit amet mattis vulputate enim nulla. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Nibh praesent tristique magna sit amet purus. At tellus at urna condimentum mattis. Tempor orci dapibus ultrices in iaculis nunc sed. Laoreet suspendisse interdum consectetur libero id faucibus. Sit amet volutpat consequat mauris nunc congue nisi vitae. Venenatis lectus magna fringilla urna porttitor rhoncus dolor. Lectus mauris ultrices eros in. Fermentum et sollicitudin ac orci phasellus egestas tellus rutrum tellus.\\n\" +\n" +
                        "                        \"\\n\" +\n" +
                        "                        \"Sit amet consectetur adipiscing elit duis tristique sollicitudin nibh. Nisi quis eleifend quam adipiscing vitae proin sagittis. Facilisis magna etiam tempor orci eu lobortis elementum nibh. Lectus mauris ultrices eros in. Tortor aliquam nulla facilisi cras fermentum odio eu feugiat pretium. At quis risus sed vulputate odio. Odio euismod lacinia at quis risus sed vulputate odio ut. Malesuada fames ac turpis egestas integer eget aliquet. Dolor sit amet consectetur adipiscing elit pellentesque habitant. Commodo ullamcorper a lacus vestibulum sed arcu. Sit amet luctus venenatis lectus magna fringilla urna porttitor. Ut placerat orci nulla pellentesque dignissim enim.");
        articleStorage.saveArticle(chargeOnTheRoad);

        ArticleTopic factFromFiction = new ArticleTopic ("Electric Vehicles - Separating Fact From Fiction");
        articleTopicStorage.saveArticleTopic(factFromFiction);

        Article commonMyths = new Article(factFromFiction, "5 common Electric Vehicle myths", "Billy Crash",
                "https://www.jojusolar.co.uk/wp-content/uploads/2018/03/myths.jpg",
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. They checks so many boxes; critical thinkers: check; problem solvers: check; collaborators: check. Fermentum leo vel orci porta non pulvinar neque laoreet. Dictum fusce ut placerat orci nulla pellentesque dignissim enim. Magna sit amet purus gravida quis blandit turpis. Pretium fusce id velit ut tortor pretium. Amet est placerat in egestas erat. Id leo in vitae turpis massa sed elementum tempus. Ut diam quam nulla porttitor massa. Ipsum nunc aliquet bibendum enim facilisis gravida neque. Hac habitasse platea dictumst quisque. Blandit turpis cursus in hac habitasse platea dictumst quisque sagittis. Egestas maecenas pharetra convallis posuere.\n" +
                        "\n" +
                        "Nunc sed augue lacus viverra vitae congue. Ultrices tincidunt arcu non sodales. Nunc non blandit massa enim nec dui nunc mattis. Varius sit amet mattis vulputate enim nulla. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Nibh praesent tristique magna sit amet purus. At tellus at urna condimentum mattis. Tempor orci dapibus ultrices in iaculis nunc sed. Laoreet suspendisse interdum consectetur libero id faucibus. Sit amet volutpat consequat mauris nunc congue nisi vitae. Venenatis lectus magna fringilla urna porttitor rhoncus dolor. Lectus mauris ultrices eros in. Fermentum et sollicitudin ac orci phasellus egestas tellus rutrum tellus.\n" +
                        "\n" +
                        "Sit amet consectetur adipiscing elit duis tristique sollicitudin nibh. Nisi quis eleifend quam adipiscing vitae proin sagittis. Facilisis magna etiam tempor orci eu lobortis elementum nibh. Lectus mauris ultrices eros in. Tortor aliquam nulla facilisi cras fermentum odio eu feugiat pretium. At quis risus sed vulputate odio. Odio euismod lacinia at quis risus sed vulputate odio ut. Malesuada fames ac turpis egestas integer eget aliquet. Dolor sit amet consectetur adipiscing elit pellentesque habitant. Commodo ullamcorper a lacus vestibulum sed arcu. Sit amet luctus venenatis lectus magna fringilla urna porttitor. Ut placerat orci nulla pellentesque dignissim enim.");
        articleStorage.saveArticle(commonMyths);

        Article mythbusters = new Article(factFromFiction, "EV Mythbusters: Who you gonna call?", "Daisy Domergue",
                "https://news-media.energysage.com/wp-content/uploads/2021/03/03.09.21-ev-myth-busted.png",
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. When you combine their Software Engineering skills with their many soft skills, you really have to ask yourself, How is this group not already our employees? Fermentum leo vel orci porta non pulvinar neque laoreet. Dictum fusce ut placerat orci nulla pellentesque dignissim enim. Magna sit amet purus gravida quis blandit turpis. Pretium fusce id velit ut tortor pretium. Amet est placerat in egestas erat. Id leo in vitae turpis massa sed elementum tempus. Ut diam quam nulla porttitor massa. Ipsum nunc aliquet bibendum enim facilisis gravida neque. Hac habitasse platea dictumst quisque. Blandit turpis cursus in hac habitasse platea dictumst quisque sagittis. Egestas maecenas pharetra convallis posuere.\n" +
                        "\n" +
                        "Nunc sed augue lacus viverra vitae congue. Ultrices tincidunt arcu non sodales. Nunc non blandit massa enim nec dui nunc mattis. Varius sit amet mattis vulputate enim nulla. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Nibh praesent tristique magna sit amet purus. At tellus at urna condimentum mattis. Tempor orci dapibus ultrices in iaculis nunc sed. Laoreet suspendisse interdum consectetur libero id faucibus. Sit amet volutpat consequat mauris nunc congue nisi vitae. Venenatis lectus magna fringilla urna porttitor rhoncus dolor. Lectus mauris ultrices eros in. Fermentum et sollicitudin ac orci phasellus egestas tellus rutrum tellus.\n" +
                        "\n" +
                        "Sit amet consectetur adipiscing elit duis tristique sollicitudin nibh. Nisi quis eleifend quam adipiscing vitae proin sagittis. Facilisis magna etiam tempor orci eu lobortis elementum nibh. Lectus mauris ultrices eros in. Tortor aliquam nulla facilisi cras fermentum odio eu feugiat pretium. At quis risus sed vulputate odio. Odio euismod lacinia at quis risus sed vulputate odio ut. Malesuada fames ac turpis egestas integer eget aliquet. Dolor sit amet consectetur adipiscing elit pellentesque habitant. Commodo ullamcorper a lacus vestibulum sed arcu. Sit amet luctus venenatis lectus magna fringilla urna porttitor. Ut placerat orci nulla pellentesque dignissim enim.");
        articleStorage.saveArticle(mythbusters);

        ReviewTopic currentlyAvailableEvs = new ReviewTopic("Currently Available EVs");
        reviewTopicStorage.saveReviewTopic(currentlyAvailableEvs);

        Review audiEtronSportback = new Review(currentlyAvailableEvs, "Audi e-tron Sportback", "Cliff Booth",
                "https://www.cnet.com/a/img/jF9XjA7gNJLQQo9ivIG6zEno4Qo=/2019/11/19/efbb58b4-bc42-46c6-8142-16ff002fd12d/ogi-audi-e-tron-sportback-2020-ogi.jpg",
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. The creators of this web application would make great additions to your Software Engineering team. Fermentum leo vel orci porta non pulvinar neque laoreet. Dictum fusce ut placerat orci nulla pellentesque dignissim enim. Magna sit amet purus gravida quis blandit turpis. Pretium fusce id velit ut tortor pretium. Amet est placerat in egestas erat. Id leo in vitae turpis massa sed elementum tempus. Ut diam quam nulla porttitor massa. Ipsum nunc aliquet bibendum enim facilisis gravida neque. Hac habitasse platea dictumst quisque. Blandit turpis cursus in hac habitasse platea dictumst quisque sagittis. Egestas maecenas pharetra convallis posuere.\n" +
                        "\n" +
                        "Nunc sed augue lacus viverra vitae congue. Ultrices tincidunt arcu non sodales. Nunc non blandit massa enim nec dui nunc mattis. Varius sit amet mattis vulputate enim nulla. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Nibh praesent tristique magna sit amet purus. At tellus at urna condimentum mattis. Tempor orci dapibus ultrices in iaculis nunc sed. Laoreet suspendisse interdum consectetur libero id faucibus. Sit amet volutpat consequat mauris nunc congue nisi vitae. Venenatis lectus magna fringilla urna porttitor rhoncus dolor. Lectus mauris ultrices eros in. Fermentum et sollicitudin ac orci phasellus egestas tellus rutrum tellus.\n" +
                        "\n" +
                        "Sit amet consectetur adipiscing elit duis tristique sollicitudin nibh. Nisi quis eleifend quam adipiscing vitae proin sagittis. Facilisis magna etiam tempor orci eu lobortis elementum nibh. Lectus mauris ultrices eros in. Tortor aliquam nulla facilisi cras fermentum odio eu feugiat pretium. At quis risus sed vulputate odio. Odio euismod lacinia at quis risus sed vulputate odio ut. Malesuada fames ac turpis egestas integer eget aliquet. Dolor sit amet consectetur adipiscing elit pellentesque habitant. Commodo ullamcorper a lacus vestibulum sed arcu. Sit amet luctus venenatis lectus magna fringilla urna porttitor. Ut placerat orci nulla pellentesque dignissim enim.");
        reviewStorage.saveReview(audiEtronSportback);

        Review chevyBolt = new Review(currentlyAvailableEvs, "Chevrolet Bolt", "Mia Wallace",
                "https://media.chevrolet.com/content/Pages/news/us/en/2021/feb/0214-boltev-bolteuv/_jcr_content/top_parsys/image.img.jpg/1613335646777.jpg",
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. They checks so many boxes; critical thinkers: check; problem solvers: check; collaborators: check. Fermentum leo vel orci porta non pulvinar neque laoreet. Dictum fusce ut placerat orci nulla pellentesque dignissim enim. Magna sit amet purus gravida quis blandit turpis. Pretium fusce id velit ut tortor pretium. Amet est placerat in egestas erat. Id leo in vitae turpis massa sed elementum tempus. Ut diam quam nulla porttitor massa. Ipsum nunc aliquet bibendum enim facilisis gravida neque. Hac habitasse platea dictumst quisque. Blandit turpis cursus in hac habitasse platea dictumst quisque sagittis. Egestas maecenas pharetra convallis posuere.\n" +
                        "\n" +
                        "Nunc sed augue lacus viverra vitae congue. Ultrices tincidunt arcu non sodales. Nunc non blandit massa enim nec dui nunc mattis. Varius sit amet mattis vulputate enim nulla. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Nibh praesent tristique magna sit amet purus. At tellus at urna condimentum mattis. Tempor orci dapibus ultrices in iaculis nunc sed. Laoreet suspendisse interdum consectetur libero id faucibus. Sit amet volutpat consequat mauris nunc congue nisi vitae. Venenatis lectus magna fringilla urna porttitor rhoncus dolor. Lectus mauris ultrices eros in. Fermentum et sollicitudin ac orci phasellus egestas tellus rutrum tellus.\n" +
                        "\n" +
                        "Sit amet consectetur adipiscing elit duis tristique sollicitudin nibh. Nisi quis eleifend quam adipiscing vitae proin sagittis. Facilisis magna etiam tempor orci eu lobortis elementum nibh. Lectus mauris ultrices eros in. Tortor aliquam nulla facilisi cras fermentum odio eu feugiat pretium. At quis risus sed vulputate odio. Odio euismod lacinia at quis risus sed vulputate odio ut. Malesuada fames ac turpis egestas integer eget aliquet. Dolor sit amet consectetur adipiscing elit pellentesque habitant. Commodo ullamcorper a lacus vestibulum sed arcu. Sit amet luctus venenatis lectus magna fringilla urna porttitor. Ut placerat orci nulla pellentesque dignissim enim.");
        reviewStorage.saveReview(chevyBolt);

        Review fordMustang = new Review(currentlyAvailableEvs, "Ford Mustang Mach-E Select (eAWD)", "Vincent Vega ",
                "https://media.ford.com/content/fordmedia/fna/us/en/products/evs/mustang-mach-e/mustang-mach-e/jcr:content/content/media-section-parsys/textimage_f597/image.img.951.535.jpg/1608221793793.jpg",
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. When you combine their Software Engineering skills with their many soft skills, you really have to ask yourself, How is this group not already our employees? Fermentum leo vel orci porta non pulvinar neque laoreet. Dictum fusce ut placerat orci nulla pellentesque dignissim enim. Magna sit amet purus gravida quis blandit turpis. Pretium fusce id velit ut tortor pretium. Amet est placerat in egestas erat. Id leo in vitae turpis massa sed elementum tempus. Ut diam quam nulla porttitor massa. Ipsum nunc aliquet bibendum enim facilisis gravida neque. Hac habitasse platea dictumst quisque. Blandit turpis cursus in hac habitasse platea dictumst quisque sagittis. Egestas maecenas pharetra convallis posuere.\n" +
                        "\n" +
                        "Nunc sed augue lacus viverra vitae congue. Ultrices tincidunt arcu non sodales. Nunc non blandit massa enim nec dui nunc mattis. Varius sit amet mattis vulputate enim nulla. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Nibh praesent tristique magna sit amet purus. At tellus at urna condimentum mattis. Tempor orci dapibus ultrices in iaculis nunc sed. Laoreet suspendisse interdum consectetur libero id faucibus. Sit amet volutpat consequat mauris nunc congue nisi vitae. Venenatis lectus magna fringilla urna porttitor rhoncus dolor. Lectus mauris ultrices eros in. Fermentum et sollicitudin ac orci phasellus egestas tellus rutrum tellus.\n" +
                        "\n" +
                        "Sit amet consectetur adipiscing elit duis tristique sollicitudin nibh. Nisi quis eleifend quam adipiscing vitae proin sagittis. Facilisis magna etiam tempor orci eu lobortis elementum nibh. Lectus mauris ultrices eros in. Tortor aliquam nulla facilisi cras fermentum odio eu feugiat pretium. At quis risus sed vulputate odio. Odio euismod lacinia at quis risus sed vulputate odio ut. Malesuada fames ac turpis egestas integer eget aliquet. Dolor sit amet consectetur adipiscing elit pellentesque habitant. Commodo ullamcorper a lacus vestibulum sed arcu. Sit amet luctus venenatis lectus magna fringilla urna porttitor. Ut placerat orci nulla pellentesque dignissim enim.");
        reviewStorage.saveReview(fordMustang);

        Review hyundaiIoniq = new Review(currentlyAvailableEvs, "Hyundai Ioniq","Joe Cabot",
                "https://media.ed.edmunds-media.com/hyundai/ioniq-hybrid/2020/oem/2020_hyundai_ioniq-hybrid_4dr-hatchback_limited_fq_oem_1_1600.jpg",
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. The creators of this web application would make great additions to your Software Engineering team. Fermentum leo vel orci porta non pulvinar neque laoreet. Dictum fusce ut placerat orci nulla pellentesque dignissim enim. Magna sit amet purus gravida quis blandit turpis. Pretium fusce id velit ut tortor pretium. Amet est placerat in egestas erat. Id leo in vitae turpis massa sed elementum tempus. Ut diam quam nulla porttitor massa. Ipsum nunc aliquet bibendum enim facilisis gravida neque. Hac habitasse platea dictumst quisque. Blandit turpis cursus in hac habitasse platea dictumst quisque sagittis. Egestas maecenas pharetra convallis posuere.\n" +
                        "\n" +
                        "Nunc sed augue lacus viverra vitae congue. Ultrices tincidunt arcu non sodales. Nunc non blandit massa enim nec dui nunc mattis. Varius sit amet mattis vulputate enim nulla. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Nibh praesent tristique magna sit amet purus. At tellus at urna condimentum mattis. Tempor orci dapibus ultrices in iaculis nunc sed. Laoreet suspendisse interdum consectetur libero id faucibus. Sit amet volutpat consequat mauris nunc congue nisi vitae. Venenatis lectus magna fringilla urna porttitor rhoncus dolor. Lectus mauris ultrices eros in. Fermentum et sollicitudin ac orci phasellus egestas tellus rutrum tellus.\n" +
                        "\n" +
                        "Sit amet consectetur adipiscing elit duis tristique sollicitudin nibh. Nisi quis eleifend quam adipiscing vitae proin sagittis. Facilisis magna etiam tempor orci eu lobortis elementum nibh. Lectus mauris ultrices eros in. Tortor aliquam nulla facilisi cras fermentum odio eu feugiat pretium. At quis risus sed vulputate odio. Odio euismod lacinia at quis risus sed vulputate odio ut. Malesuada fames ac turpis egestas integer eget aliquet. Dolor sit amet consectetur adipiscing elit pellentesque habitant. Commodo ullamcorper a lacus vestibulum sed arcu. Sit amet luctus venenatis lectus magna fringilla urna porttitor. Ut placerat orci nulla pellentesque dignissim enim.");
        reviewStorage.saveReview(hyundaiIoniq);

        Review hyundaiKona = new Review(currentlyAvailableEvs, "Hyundai Kona", "Alabama Whitman",
                "https://cdn.motor1.com/images/mgl/qz7Eg/s1/hyundai-kona-electric-restyling-2021.webp",
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. They checks so many boxes; critical thinkers: check; problem solvers: check; collaborators: check. Fermentum leo vel orci porta non pulvinar neque laoreet. Dictum fusce ut placerat orci nulla pellentesque dignissim enim. Magna sit amet purus gravida quis blandit turpis. Pretium fusce id velit ut tortor pretium. Amet est placerat in egestas erat. Id leo in vitae turpis massa sed elementum tempus. Ut diam quam nulla porttitor massa. Ipsum nunc aliquet bibendum enim facilisis gravida neque. Hac habitasse platea dictumst quisque. Blandit turpis cursus in hac habitasse platea dictumst quisque sagittis. Egestas maecenas pharetra convallis posuere.\n" +
                        "\n" +
                        "Nunc sed augue lacus viverra vitae congue. Ultrices tincidunt arcu non sodales. Nunc non blandit massa enim nec dui nunc mattis. Varius sit amet mattis vulputate enim nulla. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Nibh praesent tristique magna sit amet purus. At tellus at urna condimentum mattis. Tempor orci dapibus ultrices in iaculis nunc sed. Laoreet suspendisse interdum consectetur libero id faucibus. Sit amet volutpat consequat mauris nunc congue nisi vitae. Venenatis lectus magna fringilla urna porttitor rhoncus dolor. Lectus mauris ultrices eros in. Fermentum et sollicitudin ac orci phasellus egestas tellus rutrum tellus.\n" +
                        "\n" +
                        "Sit amet consectetur adipiscing elit duis tristique sollicitudin nibh. Nisi quis eleifend quam adipiscing vitae proin sagittis. Facilisis magna etiam tempor orci eu lobortis elementum nibh. Lectus mauris ultrices eros in. Tortor aliquam nulla facilisi cras fermentum odio eu feugiat pretium. At quis risus sed vulputate odio. Odio euismod lacinia at quis risus sed vulputate odio ut. Malesuada fames ac turpis egestas integer eget aliquet. Dolor sit amet consectetur adipiscing elit pellentesque habitant. Commodo ullamcorper a lacus vestibulum sed arcu. Sit amet luctus venenatis lectus magna fringilla urna porttitor. Ut placerat orci nulla pellentesque dignissim enim.");
        reviewStorage.saveReview(hyundaiKona);

        Review jaguarIpace = new Review(currentlyAvailableEvs, "Jaguar I-Pace", "Mallory Knox",
                "https://cdn.motor1.com/images/mgl/qvVZR/s1/jaguar-i-pace-lo-show-di-presentazione-dalle-19-del-1-marzo.jpg",
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. When you combine their Software Engineering skills with their many soft skills, you really have to ask yourself, How is this group not already our employees? Fermentum leo vel orci porta non pulvinar neque laoreet. Dictum fusce ut placerat orci nulla pellentesque dignissim enim. Magna sit amet purus gravida quis blandit turpis. Pretium fusce id velit ut tortor pretium. Amet est placerat in egestas erat. Id leo in vitae turpis massa sed elementum tempus. Ut diam quam nulla porttitor massa. Ipsum nunc aliquet bibendum enim facilisis gravida neque. Hac habitasse platea dictumst quisque. Blandit turpis cursus in hac habitasse platea dictumst quisque sagittis. Egestas maecenas pharetra convallis posuere.\n" +
                        "\n" +
                        "Nunc sed augue lacus viverra vitae congue. Ultrices tincidunt arcu non sodales. Nunc non blandit massa enim nec dui nunc mattis. Varius sit amet mattis vulputate enim nulla. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Nibh praesent tristique magna sit amet purus. At tellus at urna condimentum mattis. Tempor orci dapibus ultrices in iaculis nunc sed. Laoreet suspendisse interdum consectetur libero id faucibus. Sit amet volutpat consequat mauris nunc congue nisi vitae. Venenatis lectus magna fringilla urna porttitor rhoncus dolor. Lectus mauris ultrices eros in. Fermentum et sollicitudin ac orci phasellus egestas tellus rutrum tellus.\n" +
                        "\n" +
                        "Sit amet consectetur adipiscing elit duis tristique sollicitudin nibh. Nisi quis eleifend quam adipiscing vitae proin sagittis. Facilisis magna etiam tempor orci eu lobortis elementum nibh. Lectus mauris ultrices eros in. Tortor aliquam nulla facilisi cras fermentum odio eu feugiat pretium. At quis risus sed vulputate odio. Odio euismod lacinia at quis risus sed vulputate odio ut. Malesuada fames ac turpis egestas integer eget aliquet. Dolor sit amet consectetur adipiscing elit pellentesque habitant. Commodo ullamcorper a lacus vestibulum sed arcu. Sit amet luctus venenatis lectus magna fringilla urna porttitor. Ut placerat orci nulla pellentesque dignissim enim.");
        reviewStorage.saveReview(jaguarIpace);

        Review kiaNiro = new Review(currentlyAvailableEvs, "Kia Niro", "Seth Gecko",
                "https://electrek.co/wp-content/uploads/sites/3/2021/06/2021-Kia-Niro-EV.jpg?quality=82&strip=all",
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. The creators of this web application would make great additions to your Software Engineering team. Fermentum leo vel orci porta non pulvinar neque laoreet. Dictum fusce ut placerat orci nulla pellentesque dignissim enim. Magna sit amet purus gravida quis blandit turpis. Pretium fusce id velit ut tortor pretium. Amet est placerat in egestas erat. Id leo in vitae turpis massa sed elementum tempus. Ut diam quam nulla porttitor massa. Ipsum nunc aliquet bibendum enim facilisis gravida neque. Hac habitasse platea dictumst quisque. Blandit turpis cursus in hac habitasse platea dictumst quisque sagittis. Egestas maecenas pharetra convallis posuere.\n" +
                        "\n" +
                        "Nunc sed augue lacus viverra vitae congue. Ultrices tincidunt arcu non sodales. Nunc non blandit massa enim nec dui nunc mattis. Varius sit amet mattis vulputate enim nulla. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Nibh praesent tristique magna sit amet purus. At tellus at urna condimentum mattis. Tempor orci dapibus ultrices in iaculis nunc sed. Laoreet suspendisse interdum consectetur libero id faucibus. Sit amet volutpat consequat mauris nunc congue nisi vitae. Venenatis lectus magna fringilla urna porttitor rhoncus dolor. Lectus mauris ultrices eros in. Fermentum et sollicitudin ac orci phasellus egestas tellus rutrum tellus.\n" +
                        "\n" +
                        "Sit amet consectetur adipiscing elit duis tristique sollicitudin nibh. Nisi quis eleifend quam adipiscing vitae proin sagittis. Facilisis magna etiam tempor orci eu lobortis elementum nibh. Lectus mauris ultrices eros in. Tortor aliquam nulla facilisi cras fermentum odio eu feugiat pretium. At quis risus sed vulputate odio. Odio euismod lacinia at quis risus sed vulputate odio ut. Malesuada fames ac turpis egestas integer eget aliquet. Dolor sit amet consectetur adipiscing elit pellentesque habitant. Commodo ullamcorper a lacus vestibulum sed arcu. Sit amet luctus venenatis lectus magna fringilla urna porttitor. Ut placerat orci nulla pellentesque dignissim enim.");
        reviewStorage.saveReview(kiaNiro);

        Review lucidAir = new Review(currentlyAvailableEvs, "Lucid Air Touring", "Kate Fuller",
                "https://i.ytimg.com/vi/X0f0LuA6Qvk/maxresdefault.jpg",
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. They checks so many boxes; critical thinkers: check; problem solvers: check; collaborators: check. Fermentum leo vel orci porta non pulvinar neque laoreet. Dictum fusce ut placerat orci nulla pellentesque dignissim enim. Magna sit amet purus gravida quis blandit turpis. Pretium fusce id velit ut tortor pretium. Amet est placerat in egestas erat. Id leo in vitae turpis massa sed elementum tempus. Ut diam quam nulla porttitor massa. Ipsum nunc aliquet bibendum enim facilisis gravida neque. Hac habitasse platea dictumst quisque. Blandit turpis cursus in hac habitasse platea dictumst quisque sagittis. Egestas maecenas pharetra convallis posuere.\n" +
                        "\n" +
                        "Nunc sed augue lacus viverra vitae congue. Ultrices tincidunt arcu non sodales. Nunc non blandit massa enim nec dui nunc mattis. Varius sit amet mattis vulputate enim nulla. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Nibh praesent tristique magna sit amet purus. At tellus at urna condimentum mattis. Tempor orci dapibus ultrices in iaculis nunc sed. Laoreet suspendisse interdum consectetur libero id faucibus. Sit amet volutpat consequat mauris nunc congue nisi vitae. Venenatis lectus magna fringilla urna porttitor rhoncus dolor. Lectus mauris ultrices eros in. Fermentum et sollicitudin ac orci phasellus egestas tellus rutrum tellus.\n" +
                        "\n" +
                        "Sit amet consectetur adipiscing elit duis tristique sollicitudin nibh. Nisi quis eleifend quam adipiscing vitae proin sagittis. Facilisis magna etiam tempor orci eu lobortis elementum nibh. Lectus mauris ultrices eros in. Tortor aliquam nulla facilisi cras fermentum odio eu feugiat pretium. At quis risus sed vulputate odio. Odio euismod lacinia at quis risus sed vulputate odio ut. Malesuada fames ac turpis egestas integer eget aliquet. Dolor sit amet consectetur adipiscing elit pellentesque habitant. Commodo ullamcorper a lacus vestibulum sed arcu. Sit amet luctus venenatis lectus magna fringilla urna porttitor. Ut placerat orci nulla pellentesque dignissim enim.");
        reviewStorage.saveReview(lucidAir);

        Review miniCooper = new Review(currentlyAvailableEvs, "Mini Cooper SE", "Santanico Pandemonium",
                "https://cdn.motor1.com/images/mgl/kNN7x/s1/mini-cooper-se.jpg",
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. When you combine their Software Engineering skills with their many soft skills, you really have to ask yourself, How is this group not already our employees? Fermentum leo vel orci porta non pulvinar neque laoreet. Dictum fusce ut placerat orci nulla pellentesque dignissim enim. Magna sit amet purus gravida quis blandit turpis. Pretium fusce id velit ut tortor pretium. Amet est placerat in egestas erat. Id leo in vitae turpis massa sed elementum tempus. Ut diam quam nulla porttitor massa. Ipsum nunc aliquet bibendum enim facilisis gravida neque. Hac habitasse platea dictumst quisque. Blandit turpis cursus in hac habitasse platea dictumst quisque sagittis. Egestas maecenas pharetra convallis posuere.\n" +
                        "\n" +
                        "Nunc sed augue lacus viverra vitae congue. Ultrices tincidunt arcu non sodales. Nunc non blandit massa enim nec dui nunc mattis. Varius sit amet mattis vulputate enim nulla. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Nibh praesent tristique magna sit amet purus. At tellus at urna condimentum mattis. Tempor orci dapibus ultrices in iaculis nunc sed. Laoreet suspendisse interdum consectetur libero id faucibus. Sit amet volutpat consequat mauris nunc congue nisi vitae. Venenatis lectus magna fringilla urna porttitor rhoncus dolor. Lectus mauris ultrices eros in. Fermentum et sollicitudin ac orci phasellus egestas tellus rutrum tellus.\n" +
                        "\n" +
                        "Sit amet consectetur adipiscing elit duis tristique sollicitudin nibh. Nisi quis eleifend quam adipiscing vitae proin sagittis. Facilisis magna etiam tempor orci eu lobortis elementum nibh. Lectus mauris ultrices eros in. Tortor aliquam nulla facilisi cras fermentum odio eu feugiat pretium. At quis risus sed vulputate odio. Odio euismod lacinia at quis risus sed vulputate odio ut. Malesuada fames ac turpis egestas integer eget aliquet. Dolor sit amet consectetur adipiscing elit pellentesque habitant. Commodo ullamcorper a lacus vestibulum sed arcu. Sit amet luctus venenatis lectus magna fringilla urna porttitor. Ut placerat orci nulla pellentesque dignissim enim.");
        reviewStorage.saveReview(miniCooper);

        Review nissanLeaf = new Review(currentlyAvailableEvs, "Nissan Leaf S Plus", "Max Cherry",
                "https://cdn.motor1.com/images/mgl/42lOZ/s1/2021-nissan-leaf.jpg",
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. The creators of this web application would make great additions to your Software Engineering team. Fermentum leo vel orci porta non pulvinar neque laoreet. Dictum fusce ut placerat orci nulla pellentesque dignissim enim. Magna sit amet purus gravida quis blandit turpis. Pretium fusce id velit ut tortor pretium. Amet est placerat in egestas erat. Id leo in vitae turpis massa sed elementum tempus. Ut diam quam nulla porttitor massa. Ipsum nunc aliquet bibendum enim facilisis gravida neque. Hac habitasse platea dictumst quisque. Blandit turpis cursus in hac habitasse platea dictumst quisque sagittis. Egestas maecenas pharetra convallis posuere.\n" +
                        "\n" +
                        "Nunc sed augue lacus viverra vitae congue. Ultrices tincidunt arcu non sodales. Nunc non blandit massa enim nec dui nunc mattis. Varius sit amet mattis vulputate enim nulla. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Nibh praesent tristique magna sit amet purus. At tellus at urna condimentum mattis. Tempor orci dapibus ultrices in iaculis nunc sed. Laoreet suspendisse interdum consectetur libero id faucibus. Sit amet volutpat consequat mauris nunc congue nisi vitae. Venenatis lectus magna fringilla urna porttitor rhoncus dolor. Lectus mauris ultrices eros in. Fermentum et sollicitudin ac orci phasellus egestas tellus rutrum tellus.\n" +
                        "\n" +
                        "Sit amet consectetur adipiscing elit duis tristique sollicitudin nibh. Nisi quis eleifend quam adipiscing vitae proin sagittis. Facilisis magna etiam tempor orci eu lobortis elementum nibh. Lectus mauris ultrices eros in. Tortor aliquam nulla facilisi cras fermentum odio eu feugiat pretium. At quis risus sed vulputate odio. Odio euismod lacinia at quis risus sed vulputate odio ut. Malesuada fames ac turpis egestas integer eget aliquet. Dolor sit amet consectetur adipiscing elit pellentesque habitant. Commodo ullamcorper a lacus vestibulum sed arcu. Sit amet luctus venenatis lectus magna fringilla urna porttitor. Ut placerat orci nulla pellentesque dignissim enim.");
        reviewStorage.saveReview(nissanLeaf);

        Review polestar = new Review(currentlyAvailableEvs, "Polestar 2", "Ray Nicolette",
                "https://i.insider.com/5f36af5fe89ebf001f04496b?width=1136&format=jpeg",
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. They checks so many boxes; critical thinkers: check; problem solvers: check; collaborators: check. Fermentum leo vel orci porta non pulvinar neque laoreet. Dictum fusce ut placerat orci nulla pellentesque dignissim enim. Magna sit amet purus gravida quis blandit turpis. Pretium fusce id velit ut tortor pretium. Amet est placerat in egestas erat. Id leo in vitae turpis massa sed elementum tempus. Ut diam quam nulla porttitor massa. Ipsum nunc aliquet bibendum enim facilisis gravida neque. Hac habitasse platea dictumst quisque. Blandit turpis cursus in hac habitasse platea dictumst quisque sagittis. Egestas maecenas pharetra convallis posuere.\n" +
                        "\n" +
                        "Nunc sed augue lacus viverra vitae congue. Ultrices tincidunt arcu non sodales. Nunc non blandit massa enim nec dui nunc mattis. Varius sit amet mattis vulputate enim nulla. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Nibh praesent tristique magna sit amet purus. At tellus at urna condimentum mattis. Tempor orci dapibus ultrices in iaculis nunc sed. Laoreet suspendisse interdum consectetur libero id faucibus. Sit amet volutpat consequat mauris nunc congue nisi vitae. Venenatis lectus magna fringilla urna porttitor rhoncus dolor. Lectus mauris ultrices eros in. Fermentum et sollicitudin ac orci phasellus egestas tellus rutrum tellus.\n" +
                        "\n" +
                        "Sit amet consectetur adipiscing elit duis tristique sollicitudin nibh. Nisi quis eleifend quam adipiscing vitae proin sagittis. Facilisis magna etiam tempor orci eu lobortis elementum nibh. Lectus mauris ultrices eros in. Tortor aliquam nulla facilisi cras fermentum odio eu feugiat pretium. At quis risus sed vulputate odio. Odio euismod lacinia at quis risus sed vulputate odio ut. Malesuada fames ac turpis egestas integer eget aliquet. Dolor sit amet consectetur adipiscing elit pellentesque habitant. Commodo ullamcorper a lacus vestibulum sed arcu. Sit amet luctus venenatis lectus magna fringilla urna porttitor. Ut placerat orci nulla pellentesque dignissim enim.");
        reviewStorage.saveReview(polestar);

        Review porscheTaycan = new Review(currentlyAvailableEvs, "Porsche Taycan 4s", "Elle Driver",
                "https://s3-prod-europe.autonews.com/s3fs-public/taycan_cross_2.jpg",
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. When you combine their Software Engineering skills with their many soft skills, you really have to ask yourself, How is this group not already our employees? Fermentum leo vel orci porta non pulvinar neque laoreet. Dictum fusce ut placerat orci nulla pellentesque dignissim enim. Magna sit amet purus gravida quis blandit turpis. Pretium fusce id velit ut tortor pretium. Amet est placerat in egestas erat. Id leo in vitae turpis massa sed elementum tempus. Ut diam quam nulla porttitor massa. Ipsum nunc aliquet bibendum enim facilisis gravida neque. Hac habitasse platea dictumst quisque. Blandit turpis cursus in hac habitasse platea dictumst quisque sagittis. Egestas maecenas pharetra convallis posuere.\n" +
                        "\n" +
                        "Nunc sed augue lacus viverra vitae congue. Ultrices tincidunt arcu non sodales. Nunc non blandit massa enim nec dui nunc mattis. Varius sit amet mattis vulputate enim nulla. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Nibh praesent tristique magna sit amet purus. At tellus at urna condimentum mattis. Tempor orci dapibus ultrices in iaculis nunc sed. Laoreet suspendisse interdum consectetur libero id faucibus. Sit amet volutpat consequat mauris nunc congue nisi vitae. Venenatis lectus magna fringilla urna porttitor rhoncus dolor. Lectus mauris ultrices eros in. Fermentum et sollicitudin ac orci phasellus egestas tellus rutrum tellus.\n" +
                        "\n" +
                        "Sit amet consectetur adipiscing elit duis tristique sollicitudin nibh. Nisi quis eleifend quam adipiscing vitae proin sagittis. Facilisis magna etiam tempor orci eu lobortis elementum nibh. Lectus mauris ultrices eros in. Tortor aliquam nulla facilisi cras fermentum odio eu feugiat pretium. At quis risus sed vulputate odio. Odio euismod lacinia at quis risus sed vulputate odio ut. Malesuada fames ac turpis egestas integer eget aliquet. Dolor sit amet consectetur adipiscing elit pellentesque habitant. Commodo ullamcorper a lacus vestibulum sed arcu. Sit amet luctus venenatis lectus magna fringilla urna porttitor. Ut placerat orci nulla pellentesque dignissim enim.");
        reviewStorage.saveReview(porscheTaycan);

        Review teslaThree = new Review(currentlyAvailableEvs, "Tesla Model 3 SR+", "Aldo Raine",
                "https://cdn.mos.cms.futurecdn.net/yX7odtjFCfE9fZZpDtsda6.jpg",
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. The creators of this web application would make great additions to your Software Engineering team. Fermentum leo vel orci porta non pulvinar neque laoreet. Dictum fusce ut placerat orci nulla pellentesque dignissim enim. Magna sit amet purus gravida quis blandit turpis. Pretium fusce id velit ut tortor pretium. Amet est placerat in egestas erat. Id leo in vitae turpis massa sed elementum tempus. Ut diam quam nulla porttitor massa. Ipsum nunc aliquet bibendum enim facilisis gravida neque. Hac habitasse platea dictumst quisque. Blandit turpis cursus in hac habitasse platea dictumst quisque sagittis. Egestas maecenas pharetra convallis posuere.\n" +
                        "\n" +
                        "Nunc sed augue lacus viverra vitae congue. Ultrices tincidunt arcu non sodales. Nunc non blandit massa enim nec dui nunc mattis. Varius sit amet mattis vulputate enim nulla. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Nibh praesent tristique magna sit amet purus. At tellus at urna condimentum mattis. Tempor orci dapibus ultrices in iaculis nunc sed. Laoreet suspendisse interdum consectetur libero id faucibus. Sit amet volutpat consequat mauris nunc congue nisi vitae. Venenatis lectus magna fringilla urna porttitor rhoncus dolor. Lectus mauris ultrices eros in. Fermentum et sollicitudin ac orci phasellus egestas tellus rutrum tellus.\n" +
                        "\n" +
                        "Sit amet consectetur adipiscing elit duis tristique sollicitudin nibh. Nisi quis eleifend quam adipiscing vitae proin sagittis. Facilisis magna etiam tempor orci eu lobortis elementum nibh. Lectus mauris ultrices eros in. Tortor aliquam nulla facilisi cras fermentum odio eu feugiat pretium. At quis risus sed vulputate odio. Odio euismod lacinia at quis risus sed vulputate odio ut. Malesuada fames ac turpis egestas integer eget aliquet. Dolor sit amet consectetur adipiscing elit pellentesque habitant. Commodo ullamcorper a lacus vestibulum sed arcu. Sit amet luctus venenatis lectus magna fringilla urna porttitor. Ut placerat orci nulla pellentesque dignissim enim.");
        reviewStorage.saveReview(teslaThree);

        Review teslaSPlaid = new Review(currentlyAvailableEvs, "Tesla Model S Plaid", "Bridget Von Hammersmark",
                "https://motoring.pxcrush.net/motoring/general/editorial/tesla-model-s-2021.jpg?width=1024",
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. They checks so many boxes; critical thinkers: check; problem solvers: check; collaborators: check. Fermentum leo vel orci porta non pulvinar neque laoreet. Dictum fusce ut placerat orci nulla pellentesque dignissim enim. Magna sit amet purus gravida quis blandit turpis. Pretium fusce id velit ut tortor pretium. Amet est placerat in egestas erat. Id leo in vitae turpis massa sed elementum tempus. Ut diam quam nulla porttitor massa. Ipsum nunc aliquet bibendum enim facilisis gravida neque. Hac habitasse platea dictumst quisque. Blandit turpis cursus in hac habitasse platea dictumst quisque sagittis. Egestas maecenas pharetra convallis posuere.\n" +
                        "\n" +
                        "Nunc sed augue lacus viverra vitae congue. Ultrices tincidunt arcu non sodales. Nunc non blandit massa enim nec dui nunc mattis. Varius sit amet mattis vulputate enim nulla. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Nibh praesent tristique magna sit amet purus. At tellus at urna condimentum mattis. Tempor orci dapibus ultrices in iaculis nunc sed. Laoreet suspendisse interdum consectetur libero id faucibus. Sit amet volutpat consequat mauris nunc congue nisi vitae. Venenatis lectus magna fringilla urna porttitor rhoncus dolor. Lectus mauris ultrices eros in. Fermentum et sollicitudin ac orci phasellus egestas tellus rutrum tellus.\n" +
                        "\n" +
                        "Sit amet consectetur adipiscing elit duis tristique sollicitudin nibh. Nisi quis eleifend quam adipiscing vitae proin sagittis. Facilisis magna etiam tempor orci eu lobortis elementum nibh. Lectus mauris ultrices eros in. Tortor aliquam nulla facilisi cras fermentum odio eu feugiat pretium. At quis risus sed vulputate odio. Odio euismod lacinia at quis risus sed vulputate odio ut. Malesuada fames ac turpis egestas integer eget aliquet. Dolor sit amet consectetur adipiscing elit pellentesque habitant. Commodo ullamcorper a lacus vestibulum sed arcu. Sit amet luctus venenatis lectus magna fringilla urna porttitor. Ut placerat orci nulla pellentesque dignissim enim.");
        reviewStorage.saveReview(teslaSPlaid);

        Review teslaX = new Review(currentlyAvailableEvs, "Tesla Model X LR", "Calvin Candie",
                "https://i.guim.co.uk/img/media/202f28f9d64bcbf12340369c1dfc91c306bc3d49/122_245_1666_999/master/1666.jpg?width=1200&height=900&quality=85&auto=format&fit=crop&s=c80bca7e348e480a531673976412f90c",
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. When you combine their Software Engineering skills with their many soft skills, you really have to ask yourself, How is this group not already our employees? Fermentum leo vel orci porta non pulvinar neque laoreet. Dictum fusce ut placerat orci nulla pellentesque dignissim enim. Magna sit amet purus gravida quis blandit turpis. Pretium fusce id velit ut tortor pretium. Amet est placerat in egestas erat. Id leo in vitae turpis massa sed elementum tempus. Ut diam quam nulla porttitor massa. Ipsum nunc aliquet bibendum enim facilisis gravida neque. Hac habitasse platea dictumst quisque. Blandit turpis cursus in hac habitasse platea dictumst quisque sagittis. Egestas maecenas pharetra convallis posuere.\n" +
                        "\n" +
                        "Nunc sed augue lacus viverra vitae congue. Ultrices tincidunt arcu non sodales. Nunc non blandit massa enim nec dui nunc mattis. Varius sit amet mattis vulputate enim nulla. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Nibh praesent tristique magna sit amet purus. At tellus at urna condimentum mattis. Tempor orci dapibus ultrices in iaculis nunc sed. Laoreet suspendisse interdum consectetur libero id faucibus. Sit amet volutpat consequat mauris nunc congue nisi vitae. Venenatis lectus magna fringilla urna porttitor rhoncus dolor. Lectus mauris ultrices eros in. Fermentum et sollicitudin ac orci phasellus egestas tellus rutrum tellus.\n" +
                        "\n" +
                        "Sit amet consectetur adipiscing elit duis tristique sollicitudin nibh. Nisi quis eleifend quam adipiscing vitae proin sagittis. Facilisis magna etiam tempor orci eu lobortis elementum nibh. Lectus mauris ultrices eros in. Tortor aliquam nulla facilisi cras fermentum odio eu feugiat pretium. At quis risus sed vulputate odio. Odio euismod lacinia at quis risus sed vulputate odio ut. Malesuada fames ac turpis egestas integer eget aliquet. Dolor sit amet consectetur adipiscing elit pellentesque habitant. Commodo ullamcorper a lacus vestibulum sed arcu. Sit amet luctus venenatis lectus magna fringilla urna porttitor. Ut placerat orci nulla pellentesque dignissim enim.");
        reviewStorage.saveReview(teslaX);

        Review teslaY = new Review(currentlyAvailableEvs, "Tesla Model Y LR", "Marquis Warren",
                "https://cdn.motor1.com/images/mgl/Bjw4A/s1/tesla-model-y.jpg",
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. The creators of this web application would make great additions to your Software Engineering team. Fermentum leo vel orci porta non pulvinar neque laoreet. Dictum fusce ut placerat orci nulla pellentesque dignissim enim. Magna sit amet purus gravida quis blandit turpis. Pretium fusce id velit ut tortor pretium. Amet est placerat in egestas erat. Id leo in vitae turpis massa sed elementum tempus. Ut diam quam nulla porttitor massa. Ipsum nunc aliquet bibendum enim facilisis gravida neque. Hac habitasse platea dictumst quisque. Blandit turpis cursus in hac habitasse platea dictumst quisque sagittis. Egestas maecenas pharetra convallis posuere.\n" +
                        "\n" +
                        "Nunc sed augue lacus viverra vitae congue. Ultrices tincidunt arcu non sodales. Nunc non blandit massa enim nec dui nunc mattis. Varius sit amet mattis vulputate enim nulla. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Nibh praesent tristique magna sit amet purus. At tellus at urna condimentum mattis. Tempor orci dapibus ultrices in iaculis nunc sed. Laoreet suspendisse interdum consectetur libero id faucibus. Sit amet volutpat consequat mauris nunc congue nisi vitae. Venenatis lectus magna fringilla urna porttitor rhoncus dolor. Lectus mauris ultrices eros in. Fermentum et sollicitudin ac orci phasellus egestas tellus rutrum tellus.\n" +
                        "\n" +
                        "Sit amet consectetur adipiscing elit duis tristique sollicitudin nibh. Nisi quis eleifend quam adipiscing vitae proin sagittis. Facilisis magna etiam tempor orci eu lobortis elementum nibh. Lectus mauris ultrices eros in. Tortor aliquam nulla facilisi cras fermentum odio eu feugiat pretium. At quis risus sed vulputate odio. Odio euismod lacinia at quis risus sed vulputate odio ut. Malesuada fames ac turpis egestas integer eget aliquet. Dolor sit amet consectetur adipiscing elit pellentesque habitant. Commodo ullamcorper a lacus vestibulum sed arcu. Sit amet luctus venenatis lectus magna fringilla urna porttitor. Ut placerat orci nulla pellentesque dignissim enim.");
        reviewStorage.saveReview(teslaY);

        Review volksId = new Review(currentlyAvailableEvs, "Volkswagen ID.4", "Chris Mannix",
                "https://cdn.vox-cdn.com/thumbor/xR4t-SjdEMKcIjFPcVQgBLOYVk0=/0x0:1080x809/1200x800/filters:focal(454x319:626x491)/cdn.vox-cdn.com/uploads/chorus_image/image/67274209/VW_ID4_Uncovered_2_copy.0.jpg",
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. They checks so many boxes; critical thinkers: check; problem solvers: check; collaborators: check. Fermentum leo vel orci porta non pulvinar neque laoreet. Dictum fusce ut placerat orci nulla pellentesque dignissim enim. Magna sit amet purus gravida quis blandit turpis. Pretium fusce id velit ut tortor pretium. Amet est placerat in egestas erat. Id leo in vitae turpis massa sed elementum tempus. Ut diam quam nulla porttitor massa. Ipsum nunc aliquet bibendum enim facilisis gravida neque. Hac habitasse platea dictumst quisque. Blandit turpis cursus in hac habitasse platea dictumst quisque sagittis. Egestas maecenas pharetra convallis posuere.\n" +
                        "\n" +
                        "Nunc sed augue lacus viverra vitae congue. Ultrices tincidunt arcu non sodales. Nunc non blandit massa enim nec dui nunc mattis. Varius sit amet mattis vulputate enim nulla. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Nibh praesent tristique magna sit amet purus. At tellus at urna condimentum mattis. Tempor orci dapibus ultrices in iaculis nunc sed. Laoreet suspendisse interdum consectetur libero id faucibus. Sit amet volutpat consequat mauris nunc congue nisi vitae. Venenatis lectus magna fringilla urna porttitor rhoncus dolor. Lectus mauris ultrices eros in. Fermentum et sollicitudin ac orci phasellus egestas tellus rutrum tellus.\n" +
                        "\n" +
                        "Sit amet consectetur adipiscing elit duis tristique sollicitudin nibh. Nisi quis eleifend quam adipiscing vitae proin sagittis. Facilisis magna etiam tempor orci eu lobortis elementum nibh. Lectus mauris ultrices eros in. Tortor aliquam nulla facilisi cras fermentum odio eu feugiat pretium. At quis risus sed vulputate odio. Odio euismod lacinia at quis risus sed vulputate odio ut. Malesuada fames ac turpis egestas integer eget aliquet. Dolor sit amet consectetur adipiscing elit pellentesque habitant. Commodo ullamcorper a lacus vestibulum sed arcu. Sit amet luctus venenatis lectus magna fringilla urna porttitor. Ut placerat orci nulla pellentesque dignissim enim.");
        reviewStorage.saveReview(volksId);

        Review volvoXcForty = new Review(currentlyAvailableEvs, "Volvo XC40 Recharge", "Joe Gage",
                "https://assets.volvocars.com/au/~/media/australia/images/blog-i-roll/2020/july/xc40_recharge_plug-in_hybrid---main-image950x497.jpg?h=497&la=en-AU&mw=950&w=950",
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. When you combine their Software Engineering skills with their many soft skills, you really have to ask yourself, How is this group not already our employees? Fermentum leo vel orci porta non pulvinar neque laoreet. Dictum fusce ut placerat orci nulla pellentesque dignissim enim. Magna sit amet purus gravida quis blandit turpis. Pretium fusce id velit ut tortor pretium. Amet est placerat in egestas erat. Id leo in vitae turpis massa sed elementum tempus. Ut diam quam nulla porttitor massa. Ipsum nunc aliquet bibendum enim facilisis gravida neque. Hac habitasse platea dictumst quisque. Blandit turpis cursus in hac habitasse platea dictumst quisque sagittis. Egestas maecenas pharetra convallis posuere.\n" +
                        "\n" +
                        "Nunc sed augue lacus viverra vitae congue. Ultrices tincidunt arcu non sodales. Nunc non blandit massa enim nec dui nunc mattis. Varius sit amet mattis vulputate enim nulla. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Nibh praesent tristique magna sit amet purus. At tellus at urna condimentum mattis. Tempor orci dapibus ultrices in iaculis nunc sed. Laoreet suspendisse interdum consectetur libero id faucibus. Sit amet volutpat consequat mauris nunc congue nisi vitae. Venenatis lectus magna fringilla urna porttitor rhoncus dolor. Lectus mauris ultrices eros in. Fermentum et sollicitudin ac orci phasellus egestas tellus rutrum tellus.\n" +
                        "\n" +
                        "Sit amet consectetur adipiscing elit duis tristique sollicitudin nibh. Nisi quis eleifend quam adipiscing vitae proin sagittis. Facilisis magna etiam tempor orci eu lobortis elementum nibh. Lectus mauris ultrices eros in. Tortor aliquam nulla facilisi cras fermentum odio eu feugiat pretium. At quis risus sed vulputate odio. Odio euismod lacinia at quis risus sed vulputate odio ut. Malesuada fames ac turpis egestas integer eget aliquet. Dolor sit amet consectetur adipiscing elit pellentesque habitant. Commodo ullamcorper a lacus vestibulum sed arcu. Sit amet luctus venenatis lectus magna fringilla urna porttitor. Ut placerat orci nulla pellentesque dignissim enim.");
        reviewStorage.saveReview(volvoXcForty);

        ReviewTopic upcomingEvs = new ReviewTopic("Upcoming EVs");
        reviewTopicStorage.saveReviewTopic(upcomingEvs);

        Review audiA6Etron = new Review(upcomingEvs, "Audi A6 e-tron", "Minnie Mink",
                "https://assets.newatlas.com/dims4/default/d8067d3/2147483647/strip/true/crop/974x649+37+105/resize/1200x800!/quality/90/?url=http%3A%2F%2Fnewatlas-brightspot.s3.amazonaws.com%2F82%2Fe9%2Fa4b5bf1141f29737e05d03ae7345%2Fscreen-shot-2021-04-19-at-7.39.34%20PM.png",
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. The creators of this web application would make great additions to your Software Engineering team. Fermentum leo vel orci porta non pulvinar neque laoreet. Dictum fusce ut placerat orci nulla pellentesque dignissim enim. Magna sit amet purus gravida quis blandit turpis. Pretium fusce id velit ut tortor pretium. Amet est placerat in egestas erat. Id leo in vitae turpis massa sed elementum tempus. Ut diam quam nulla porttitor massa. Ipsum nunc aliquet bibendum enim facilisis gravida neque. Hac habitasse platea dictumst quisque. Blandit turpis cursus in hac habitasse platea dictumst quisque sagittis. Egestas maecenas pharetra convallis posuere.\n" +
                        "\n" +
                        "Nunc sed augue lacus viverra vitae congue. Ultrices tincidunt arcu non sodales. Nunc non blandit massa enim nec dui nunc mattis. Varius sit amet mattis vulputate enim nulla. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Nibh praesent tristique magna sit amet purus. At tellus at urna condimentum mattis. Tempor orci dapibus ultrices in iaculis nunc sed. Laoreet suspendisse interdum consectetur libero id faucibus. Sit amet volutpat consequat mauris nunc congue nisi vitae. Venenatis lectus magna fringilla urna porttitor rhoncus dolor. Lectus mauris ultrices eros in. Fermentum et sollicitudin ac orci phasellus egestas tellus rutrum tellus.\n" +
                        "\n" +
                        "Sit amet consectetur adipiscing elit duis tristique sollicitudin nibh. Nisi quis eleifend quam adipiscing vitae proin sagittis. Facilisis magna etiam tempor orci eu lobortis elementum nibh. Lectus mauris ultrices eros in. Tortor aliquam nulla facilisi cras fermentum odio eu feugiat pretium. At quis risus sed vulputate odio. Odio euismod lacinia at quis risus sed vulputate odio ut. Malesuada fames ac turpis egestas integer eget aliquet. Dolor sit amet consectetur adipiscing elit pellentesque habitant. Commodo ullamcorper a lacus vestibulum sed arcu. Sit amet luctus venenatis lectus magna fringilla urna porttitor. Ut placerat orci nulla pellentesque dignissim enim.");
        reviewStorage.saveReview(audiA6Etron);

        Review bmwIFour = new Review(upcomingEvs, "BMW I4", "Patrick Bateman",
                "https://evglobe.com/wp-content/uploads/2020/09/bmw-i4-m-electric-1700x956.jpg",
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. They checks so many boxes; critical thinkers: check; problem solvers: check; collaborators: check. Fermentum leo vel orci porta non pulvinar neque laoreet. Dictum fusce ut placerat orci nulla pellentesque dignissim enim. Magna sit amet purus gravida quis blandit turpis. Pretium fusce id velit ut tortor pretium. Amet est placerat in egestas erat. Id leo in vitae turpis massa sed elementum tempus. Ut diam quam nulla porttitor massa. Ipsum nunc aliquet bibendum enim facilisis gravida neque. Hac habitasse platea dictumst quisque. Blandit turpis cursus in hac habitasse platea dictumst quisque sagittis. Egestas maecenas pharetra convallis posuere.\n" +
                        "\n" +
                        "Nunc sed augue lacus viverra vitae congue. Ultrices tincidunt arcu non sodales. Nunc non blandit massa enim nec dui nunc mattis. Varius sit amet mattis vulputate enim nulla. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Nibh praesent tristique magna sit amet purus. At tellus at urna condimentum mattis. Tempor orci dapibus ultrices in iaculis nunc sed. Laoreet suspendisse interdum consectetur libero id faucibus. Sit amet volutpat consequat mauris nunc congue nisi vitae. Venenatis lectus magna fringilla urna porttitor rhoncus dolor. Lectus mauris ultrices eros in. Fermentum et sollicitudin ac orci phasellus egestas tellus rutrum tellus.\n" +
                        "\n" +
                        "Sit amet consectetur adipiscing elit duis tristique sollicitudin nibh. Nisi quis eleifend quam adipiscing vitae proin sagittis. Facilisis magna etiam tempor orci eu lobortis elementum nibh. Lectus mauris ultrices eros in. Tortor aliquam nulla facilisi cras fermentum odio eu feugiat pretium. At quis risus sed vulputate odio. Odio euismod lacinia at quis risus sed vulputate odio ut. Malesuada fames ac turpis egestas integer eget aliquet. Dolor sit amet consectetur adipiscing elit pellentesque habitant. Commodo ullamcorper a lacus vestibulum sed arcu. Sit amet luctus venenatis lectus magna fringilla urna porttitor. Ut placerat orci nulla pellentesque dignissim enim.");
        reviewStorage.saveReview(bmwIFour);

        Review bmwIx = new Review(upcomingEvs, "BMW IX", "Timothy Bryce",
                "https://cdn.vox-cdn.com/thumbor/VuSodeasyFU7eraSHHxeV7tYVE0=/1400x1400/filters:format(jpeg)/cdn.vox-cdn.com/uploads/chorus_asset/file/22551750/P90422118_highRes.jpg",
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. When you combine their Software Engineering skills with their many soft skills, you really have to ask yourself, How is this group not already our employees? Fermentum leo vel orci porta non pulvinar neque laoreet. Dictum fusce ut placerat orci nulla pellentesque dignissim enim. Magna sit amet purus gravida quis blandit turpis. Pretium fusce id velit ut tortor pretium. Amet est placerat in egestas erat. Id leo in vitae turpis massa sed elementum tempus. Ut diam quam nulla porttitor massa. Ipsum nunc aliquet bibendum enim facilisis gravida neque. Hac habitasse platea dictumst quisque. Blandit turpis cursus in hac habitasse platea dictumst quisque sagittis. Egestas maecenas pharetra convallis posuere.\n" +
                        "\n" +
                        "Nunc sed augue lacus viverra vitae congue. Ultrices tincidunt arcu non sodales. Nunc non blandit massa enim nec dui nunc mattis. Varius sit amet mattis vulputate enim nulla. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Nibh praesent tristique magna sit amet purus. At tellus at urna condimentum mattis. Tempor orci dapibus ultrices in iaculis nunc sed. Laoreet suspendisse interdum consectetur libero id faucibus. Sit amet volutpat consequat mauris nunc congue nisi vitae. Venenatis lectus magna fringilla urna porttitor rhoncus dolor. Lectus mauris ultrices eros in. Fermentum et sollicitudin ac orci phasellus egestas tellus rutrum tellus.\n" +
                        "\n" +
                        "Sit amet consectetur adipiscing elit duis tristique sollicitudin nibh. Nisi quis eleifend quam adipiscing vitae proin sagittis. Facilisis magna etiam tempor orci eu lobortis elementum nibh. Lectus mauris ultrices eros in. Tortor aliquam nulla facilisi cras fermentum odio eu feugiat pretium. At quis risus sed vulputate odio. Odio euismod lacinia at quis risus sed vulputate odio ut. Malesuada fames ac turpis egestas integer eget aliquet. Dolor sit amet consectetur adipiscing elit pellentesque habitant. Commodo ullamcorper a lacus vestibulum sed arcu. Sit amet luctus venenatis lectus magna fringilla urna porttitor. Ut placerat orci nulla pellentesque dignissim enim.");
        reviewStorage.saveReview(bmwIx);

        Review bollinger = new Review(upcomingEvs, "Bollinger B2", "Paul Allen",
                "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/bollinger-b2-3-4-front-1569523201.jpg",
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. The creators of this web application would make great additions to your Software Engineering team. Fermentum leo vel orci porta non pulvinar neque laoreet. Dictum fusce ut placerat orci nulla pellentesque dignissim enim. Magna sit amet purus gravida quis blandit turpis. Pretium fusce id velit ut tortor pretium. Amet est placerat in egestas erat. Id leo in vitae turpis massa sed elementum tempus. Ut diam quam nulla porttitor massa. Ipsum nunc aliquet bibendum enim facilisis gravida neque. Hac habitasse platea dictumst quisque. Blandit turpis cursus in hac habitasse platea dictumst quisque sagittis. Egestas maecenas pharetra convallis posuere.\n" +
                        "\n" +
                        "Nunc sed augue lacus viverra vitae congue. Ultrices tincidunt arcu non sodales. Nunc non blandit massa enim nec dui nunc mattis. Varius sit amet mattis vulputate enim nulla. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Nibh praesent tristique magna sit amet purus. At tellus at urna condimentum mattis. Tempor orci dapibus ultrices in iaculis nunc sed. Laoreet suspendisse interdum consectetur libero id faucibus. Sit amet volutpat consequat mauris nunc congue nisi vitae. Venenatis lectus magna fringilla urna porttitor rhoncus dolor. Lectus mauris ultrices eros in. Fermentum et sollicitudin ac orci phasellus egestas tellus rutrum tellus.\n" +
                        "\n" +
                        "Sit amet consectetur adipiscing elit duis tristique sollicitudin nibh. Nisi quis eleifend quam adipiscing vitae proin sagittis. Facilisis magna etiam tempor orci eu lobortis elementum nibh. Lectus mauris ultrices eros in. Tortor aliquam nulla facilisi cras fermentum odio eu feugiat pretium. At quis risus sed vulputate odio. Odio euismod lacinia at quis risus sed vulputate odio ut. Malesuada fames ac turpis egestas integer eget aliquet. Dolor sit amet consectetur adipiscing elit pellentesque habitant. Commodo ullamcorper a lacus vestibulum sed arcu. Sit amet luctus venenatis lectus magna fringilla urna porttitor. Ut placerat orci nulla pellentesque dignissim enim.");
        reviewStorage.saveReview(bollinger);

        Review cadillac = new Review(upcomingEvs, "Cadillac Lyriq", "Sean Bateman",
                "https://www.motortrend.com/uploads/sites/5/2020/08/2023-Cadillac-Lyriq-8.jpg?fit=around%7C875:492",
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. They checks so many boxes; critical thinkers: check; problem solvers: check; collaborators: check. Fermentum leo vel orci porta non pulvinar neque laoreet. Dictum fusce ut placerat orci nulla pellentesque dignissim enim. Magna sit amet purus gravida quis blandit turpis. Pretium fusce id velit ut tortor pretium. Amet est placerat in egestas erat. Id leo in vitae turpis massa sed elementum tempus. Ut diam quam nulla porttitor massa. Ipsum nunc aliquet bibendum enim facilisis gravida neque. Hac habitasse platea dictumst quisque. Blandit turpis cursus in hac habitasse platea dictumst quisque sagittis. Egestas maecenas pharetra convallis posuere.\n" +
                        "\n" +
                        "Nunc sed augue lacus viverra vitae congue. Ultrices tincidunt arcu non sodales. Nunc non blandit massa enim nec dui nunc mattis. Varius sit amet mattis vulputate enim nulla. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Nibh praesent tristique magna sit amet purus. At tellus at urna condimentum mattis. Tempor orci dapibus ultrices in iaculis nunc sed. Laoreet suspendisse interdum consectetur libero id faucibus. Sit amet volutpat consequat mauris nunc congue nisi vitae. Venenatis lectus magna fringilla urna porttitor rhoncus dolor. Lectus mauris ultrices eros in. Fermentum et sollicitudin ac orci phasellus egestas tellus rutrum tellus.\n" +
                        "\n" +
                        "Sit amet consectetur adipiscing elit duis tristique sollicitudin nibh. Nisi quis eleifend quam adipiscing vitae proin sagittis. Facilisis magna etiam tempor orci eu lobortis elementum nibh. Lectus mauris ultrices eros in. Tortor aliquam nulla facilisi cras fermentum odio eu feugiat pretium. At quis risus sed vulputate odio. Odio euismod lacinia at quis risus sed vulputate odio ut. Malesuada fames ac turpis egestas integer eget aliquet. Dolor sit amet consectetur adipiscing elit pellentesque habitant. Commodo ullamcorper a lacus vestibulum sed arcu. Sit amet luctus venenatis lectus magna fringilla urna porttitor. Ut placerat orci nulla pellentesque dignissim enim.");
        reviewStorage.saveReview(cadillac);

        Review fordFOneFifty = new Review(upcomingEvs, "Ford F-150 Lightning", "Lauren Hynde",
                "https://thumbor.forbes.com/thumbor/fit-in/960x720/https://www.forbes.com/wheels/wp-content/uploads/2021/05/Ford_F-150_Lightning_Gallery13.jpg",
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Morbi tempus iaculis urna id volutpat lacus laoreet non curabitur. Mauris ultrices eros in cursus turpis massa tincidunt dui. Fermentum leo vel orci porta non pulvinar neque laoreet. Dictum fusce ut placerat orci nulla pellentesque dignissim enim. Magna sit amet purus gravida quis blandit turpis. Pretium fusce id velit ut tortor pretium. Amet est placerat in egestas erat. Id leo in vitae turpis massa sed elementum tempus. Ut diam quam nulla porttitor massa. Ipsum nunc aliquet bibendum enim facilisis gravida neque. Hac habitasse platea dictumst quisque. Blandit turpis cursus in hac habitasse platea dictumst quisque sagittis. Egestas maecenas pharetra convallis posuere.\n" +
                        "\n" +
                        "Nunc sed augue lacus viverra vitae congue. Ultrices tincidunt arcu non sodales. Nunc non blandit massa enim nec dui nunc mattis. Varius sit amet mattis vulputate enim nulla. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Nibh praesent tristique magna sit amet purus. At tellus at urna condimentum mattis. Tempor orci dapibus ultrices in iaculis nunc sed. Laoreet suspendisse interdum consectetur libero id faucibus. Sit amet volutpat consequat mauris nunc congue nisi vitae. Venenatis lectus magna fringilla urna porttitor rhoncus dolor. Lectus mauris ultrices eros in. Fermentum et sollicitudin ac orci phasellus egestas tellus rutrum tellus.\n" +
                        "\n" +
                        "Sit amet consectetur adipiscing elit duis tristique sollicitudin nibh. Nisi quis eleifend quam adipiscing vitae proin sagittis. Facilisis magna etiam tempor orci eu lobortis elementum nibh. Lectus mauris ultrices eros in. Tortor aliquam nulla facilisi cras fermentum odio eu feugiat pretium. At quis risus sed vulputate odio. Odio euismod lacinia at quis risus sed vulputate odio ut. Malesuada fames ac turpis egestas integer eget aliquet. Dolor sit amet consectetur adipiscing elit pellentesque habitant. Commodo ullamcorper a lacus vestibulum sed arcu. Sit amet luctus venenatis lectus magna fringilla urna porttitor. Ut placerat orci nulla pellentesque dignissim enim.");
        reviewStorage.saveReview(fordFOneFifty);

        Review genesis = new Review(upcomingEvs, "Genesis G80", "Paul Denton",
                "https://cdn.motor1.com/images/mgl/rMMlP/s3/2022-genesis-g80-sport.jpg",
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Morbi tempus iaculis urna id volutpat lacus laoreet non curabitur. Mauris ultrices eros in cursus turpis massa tincidunt dui. Fermentum leo vel orci porta non pulvinar neque laoreet. Dictum fusce ut placerat orci nulla pellentesque dignissim enim. Magna sit amet purus gravida quis blandit turpis. Pretium fusce id velit ut tortor pretium. Amet est placerat in egestas erat. Id leo in vitae turpis massa sed elementum tempus. Ut diam quam nulla porttitor massa. Ipsum nunc aliquet bibendum enim facilisis gravida neque. Hac habitasse platea dictumst quisque. Blandit turpis cursus in hac habitasse platea dictumst quisque sagittis. Egestas maecenas pharetra convallis posuere.\n" +
                        "\n" +
                        "Nunc sed augue lacus viverra vitae congue. Ultrices tincidunt arcu non sodales. Nunc non blandit massa enim nec dui nunc mattis. Varius sit amet mattis vulputate enim nulla. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Nibh praesent tristique magna sit amet purus. At tellus at urna condimentum mattis. Tempor orci dapibus ultrices in iaculis nunc sed. Laoreet suspendisse interdum consectetur libero id faucibus. Sit amet volutpat consequat mauris nunc congue nisi vitae. Venenatis lectus magna fringilla urna porttitor rhoncus dolor. Lectus mauris ultrices eros in. Fermentum et sollicitudin ac orci phasellus egestas tellus rutrum tellus.\n" +
                        "\n" +
                        "Sit amet consectetur adipiscing elit duis tristique sollicitudin nibh. Nisi quis eleifend quam adipiscing vitae proin sagittis. Facilisis magna etiam tempor orci eu lobortis elementum nibh. Lectus mauris ultrices eros in. Tortor aliquam nulla facilisi cras fermentum odio eu feugiat pretium. At quis risus sed vulputate odio. Odio euismod lacinia at quis risus sed vulputate odio ut. Malesuada fames ac turpis egestas integer eget aliquet. Dolor sit amet consectetur adipiscing elit pellentesque habitant. Commodo ullamcorper a lacus vestibulum sed arcu. Sit amet luctus venenatis lectus magna fringilla urna porttitor. Ut placerat orci nulla pellentesque dignissim enim.");
        reviewStorage.saveReview(genesis);

        Review gmcHummer = new Review(upcomingEvs, "GMC Hummer EV", "Jimmy McNulty",
                "https://media.assets.sincrod.com/websites/content/gmps-cadbuick-fl//ef684d2057a04f438dd4d02210f22a9f_1920x750.jpg",
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Morbi tempus iaculis urna id volutpat lacus laoreet non curabitur. Mauris ultrices eros in cursus turpis massa tincidunt dui. Fermentum leo vel orci porta non pulvinar neque laoreet. Dictum fusce ut placerat orci nulla pellentesque dignissim enim. Magna sit amet purus gravida quis blandit turpis. Pretium fusce id velit ut tortor pretium. Amet est placerat in egestas erat. Id leo in vitae turpis massa sed elementum tempus. Ut diam quam nulla porttitor massa. Ipsum nunc aliquet bibendum enim facilisis gravida neque. Hac habitasse platea dictumst quisque. Blandit turpis cursus in hac habitasse platea dictumst quisque sagittis. Egestas maecenas pharetra convallis posuere.\n" +
                        "\n" +
                        "Nunc sed augue lacus viverra vitae congue. Ultrices tincidunt arcu non sodales. Nunc non blandit massa enim nec dui nunc mattis. Varius sit amet mattis vulputate enim nulla. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Nibh praesent tristique magna sit amet purus. At tellus at urna condimentum mattis. Tempor orci dapibus ultrices in iaculis nunc sed. Laoreet suspendisse interdum consectetur libero id faucibus. Sit amet volutpat consequat mauris nunc congue nisi vitae. Venenatis lectus magna fringilla urna porttitor rhoncus dolor. Lectus mauris ultrices eros in. Fermentum et sollicitudin ac orci phasellus egestas tellus rutrum tellus.\n" +
                        "\n" +
                        "Sit amet consectetur adipiscing elit duis tristique sollicitudin nibh. Nisi quis eleifend quam adipiscing vitae proin sagittis. Facilisis magna etiam tempor orci eu lobortis elementum nibh. Lectus mauris ultrices eros in. Tortor aliquam nulla facilisi cras fermentum odio eu feugiat pretium. At quis risus sed vulputate odio. Odio euismod lacinia at quis risus sed vulputate odio ut. Malesuada fames ac turpis egestas integer eget aliquet. Dolor sit amet consectetur adipiscing elit pellentesque habitant. Commodo ullamcorper a lacus vestibulum sed arcu. Sit amet luctus venenatis lectus magna fringilla urna porttitor. Ut placerat orci nulla pellentesque dignissim enim.");
        reviewStorage.saveReview(gmcHummer);

        Review hyundaiIoniqFive = new Review(upcomingEvs, "Hyundai Ioniq 5", "William “Bunk” Moreland",
                "https://www.hyundai.com/content/dam/hyundai/ww/en/images/find-a-car/pip/eco/ioniq5/worldpremiere/ioniq5-ne-world-premiere-stg-m.jpg",
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Morbi tempus iaculis urna id volutpat lacus laoreet non curabitur. Mauris ultrices eros in cursus turpis massa tincidunt dui. Fermentum leo vel orci porta non pulvinar neque laoreet. Dictum fusce ut placerat orci nulla pellentesque dignissim enim. Magna sit amet purus gravida quis blandit turpis. Pretium fusce id velit ut tortor pretium. Amet est placerat in egestas erat. Id leo in vitae turpis massa sed elementum tempus. Ut diam quam nulla porttitor massa. Ipsum nunc aliquet bibendum enim facilisis gravida neque. Hac habitasse platea dictumst quisque. Blandit turpis cursus in hac habitasse platea dictumst quisque sagittis. Egestas maecenas pharetra convallis posuere.\n" +
                        "\n" +
                        "Nunc sed augue lacus viverra vitae congue. Ultrices tincidunt arcu non sodales. Nunc non blandit massa enim nec dui nunc mattis. Varius sit amet mattis vulputate enim nulla. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Nibh praesent tristique magna sit amet purus. At tellus at urna condimentum mattis. Tempor orci dapibus ultrices in iaculis nunc sed. Laoreet suspendisse interdum consectetur libero id faucibus. Sit amet volutpat consequat mauris nunc congue nisi vitae. Venenatis lectus magna fringilla urna porttitor rhoncus dolor. Lectus mauris ultrices eros in. Fermentum et sollicitudin ac orci phasellus egestas tellus rutrum tellus.\n" +
                        "\n" +
                        "Sit amet consectetur adipiscing elit duis tristique sollicitudin nibh. Nisi quis eleifend quam adipiscing vitae proin sagittis. Facilisis magna etiam tempor orci eu lobortis elementum nibh. Lectus mauris ultrices eros in. Tortor aliquam nulla facilisi cras fermentum odio eu feugiat pretium. At quis risus sed vulputate odio. Odio euismod lacinia at quis risus sed vulputate odio ut. Malesuada fames ac turpis egestas integer eget aliquet. Dolor sit amet consectetur adipiscing elit pellentesque habitant. Commodo ullamcorper a lacus vestibulum sed arcu. Sit amet luctus venenatis lectus magna fringilla urna porttitor. Ut placerat orci nulla pellentesque dignissim enim.");
        reviewStorage.saveReview(hyundaiIoniqFive);

        Review jeepMagneto = new Review(upcomingEvs, "Jeep Wrangler Magneto", "Shakima Greggs",
                "https://cdn.vox-cdn.com/uploads/chorus_asset/file/22389233/CN021_005JPphmt54ub7fcb67dcvs39kjmttl.jpg",
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Morbi tempus iaculis urna id volutpat lacus laoreet non curabitur. Mauris ultrices eros in cursus turpis massa tincidunt dui. Fermentum leo vel orci porta non pulvinar neque laoreet. Dictum fusce ut placerat orci nulla pellentesque dignissim enim. Magna sit amet purus gravida quis blandit turpis. Pretium fusce id velit ut tortor pretium. Amet est placerat in egestas erat. Id leo in vitae turpis massa sed elementum tempus. Ut diam quam nulla porttitor massa. Ipsum nunc aliquet bibendum enim facilisis gravida neque. Hac habitasse platea dictumst quisque. Blandit turpis cursus in hac habitasse platea dictumst quisque sagittis. Egestas maecenas pharetra convallis posuere.\n" +
                        "\n" +
                        "Nunc sed augue lacus viverra vitae congue. Ultrices tincidunt arcu non sodales. Nunc non blandit massa enim nec dui nunc mattis. Varius sit amet mattis vulputate enim nulla. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Nibh praesent tristique magna sit amet purus. At tellus at urna condimentum mattis. Tempor orci dapibus ultrices in iaculis nunc sed. Laoreet suspendisse interdum consectetur libero id faucibus. Sit amet volutpat consequat mauris nunc congue nisi vitae. Venenatis lectus magna fringilla urna porttitor rhoncus dolor. Lectus mauris ultrices eros in. Fermentum et sollicitudin ac orci phasellus egestas tellus rutrum tellus.\n" +
                        "\n" +
                        "Sit amet consectetur adipiscing elit duis tristique sollicitudin nibh. Nisi quis eleifend quam adipiscing vitae proin sagittis. Facilisis magna etiam tempor orci eu lobortis elementum nibh. Lectus mauris ultrices eros in. Tortor aliquam nulla facilisi cras fermentum odio eu feugiat pretium. At quis risus sed vulputate odio. Odio euismod lacinia at quis risus sed vulputate odio ut. Malesuada fames ac turpis egestas integer eget aliquet. Dolor sit amet consectetur adipiscing elit pellentesque habitant. Commodo ullamcorper a lacus vestibulum sed arcu. Sit amet luctus venenatis lectus magna fringilla urna porttitor. Ut placerat orci nulla pellentesque dignissim enim.");
        reviewStorage.saveReview(jeepMagneto);

        


    }
}
